/**
 * Does `docs/openapi.json` describe the server that actually runs.
 *
 * The document is generated by reading the `router.get('…')` calls out of the
 * source: fast, pure, and a claim about the *files*. This is the part that
 * makes it a claim about the *server* — it asks the assembled router what it
 * answers on and holds the document to it, both ways round.
 *
 * Both directions matter, and for different reasons. A route the document has
 * lost is a client that cannot call something it should be able to. A route the
 * document invented is worse: a generated client with a method that 404s, which
 * looks like a server fault to whoever wrote against it.
 */
process.env.NODE_ENV = 'test';
process.env.KOLIBRI_DATA_DIR = `/tmp/kolibri-openapi-${process.pid}`;

import assert from 'node:assert/strict';
import { readFileSync, rmSync } from 'node:fs';
import { after, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const { router, server } = await import('../src/index.ts');
const { REST_ENTITIES } = await import('@kolibri/shared');

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const spec = JSON.parse(readFileSync(join(ROOT, 'docs/openapi.json'), 'utf8')) as {
  paths: Record<string, Record<string, { operationId?: string; tags?: string[] }>>;
  components: { schemas: Record<string, unknown> };
};

after(() => {
  server.close();
  rmSync(process.env.KOLIBRI_DATA_DIR!, { recursive: true, force: true });
});

/**
 * `/api/tasks/:id` -> `/api/tasks/{id}`, the shape the document uses.
 *
 * The trailing-`*` rule is spelled here as well as in `scripts/openapi.mjs`,
 * which is duplication on purpose: the generator does its work at import and
 * cannot be imported for one helper. It is *checked* duplication — the two
 * assertions below compare the sets in both directions, so a divergence in this
 * line fails rather than passing quietly.
 */
const braced = (pattern: string) => pattern.replace(/:(\w+)/g, '{$1}').replace(/\/\*$/, '/{path}');

/**
 * The generic entity routes carry `:collection` and stand for forty of them, so
 * the document spells each one out and neither side can be compared literally.
 * Everything else is compared exactly.
 */
const generic = (pattern: string) => /^\/api\/(workspaces\/:ws\/)?:collection/.test(pattern);

describe('the OpenAPI document and the router agree', () => {
  const registered = router.registered
    .filter((route) => !generic(route.pattern))
    .map((route) => `${route.method} ${braced(route.pattern)}`);

  const documented = Object.entries(spec.paths).flatMap(([path, item]) =>
    Object.keys(item).map((method) => `${method.toUpperCase()} ${path}`));

  it('documents every route the server registers', () => {
    const missing = [...new Set(registered)].filter((route) => !documented.includes(route)).sort();
    assert.deepEqual(missing, [], `not in docs/openapi.json — run \`npm run openapi -- --fix\`:\n  ${missing.join('\n  ')}`);
  });

  it('invents none', () => {
    /*
     * The collections the document spells out resolve through the generic
     * `:collection` routes, so they are not registered literally and have to be
     * exempted — but only the ones that exist.
     *
     * The first version of this exemption was a pattern loose enough to admit
     * any single-segment path, so `GET /api/imaginary` passed as though it were
     * a collection. Built from `REST_ENTITIES` instead, the exemption is the
     * same forty names the router itself resolves, and a collection the
     * document invents fails here.
     */
    const collections = new Set(Object.keys(REST_ENTITIES));
    const throughCollection = (route: string) => {
      const match = route.match(/^(GET|POST|PATCH|DELETE) \/api\/(?:workspaces\/\{ws\}\/)?([a-z-]+)(\/\{id\})?$/);
      return !!match && collections.has(match[2]);
    };

    const invented = documented
      .filter((route) => !registered.includes(route))
      .filter((route) => !throughCollection(route))
      .sort();
    assert.deepEqual(invented, [], `in docs/openapi.json and not on the server:\n  ${invented.join('\n  ')}`);
  });

  /*
   * The one place the two halves of the document overlap.
   *
   * `GET /api/workspaces/:ws/mailboxes` is written by hand *and* is the entity
   * list route for the `mailboxes` collection. The router matches in
   * registration order, so whichever is registered first is what answers — and
   * the generator has to describe that one. It described the other for a while,
   * silently, because a duplicate looked like something to skip.
   *
   * So the rule is pinned rather than remembered: where a literal path also
   * exists as a collection, the literal registration has to come first, and the
   * document has to call it hand-written.
   */
  it('describes the route that actually answers where two claim one path', () => {
    const order = router.registered;
    const positionOf = (pattern: string) => order.findIndex((route) => route.method === 'GET' && route.pattern === pattern);

    for (const collection of Object.keys(REST_ENTITIES)) {
      const literal = `/api/workspaces/:ws/${collection}`;
      const at = positionOf(literal);
      if (at < 0) continue;

      const genericAt = positionOf('/api/workspaces/:ws/:collection');
      assert.ok(at < genericAt, `${literal} is registered after the generic route, so it never answers`);

      const documented = spec.paths[`/api/workspaces/{ws}/${collection}`]?.get as { tags?: string[] } | undefined;
      assert.ok(
        documented?.tags?.includes('hand-written'),
        `GET ${literal} is a real handler that wins, and the document describes it as the entity list route instead`,
      );
    }
  });

  it('spells out a collection the server really resolves', () => {
    // One end-to-end tie between the two: a path the document lists by name has
    // to be matched by the router through its `:collection` route.
    for (const path of ['/api/workspaces/{ws}/tasks', '/api/workspaces/{ws}/mailboxes']) {
      const concrete = path.replace('{ws}', 'w1');
      assert.ok(router.match('GET', concrete), `the router does not answer on ${concrete}`);
    }
    assert.ok(router.match('GET', '/api/tasks/t1'), 'the router does not answer on /api/tasks/:id');
  });
});
