/**
 * The single source of truth for everything that syncs.
 *
 * Server and client both derive their storage, validation and merge rules from
 * this registry, so adding a field is a one-line change in one place.
 */

export type EntityName =
  | 'user'
  | 'member'
  | 'team'
  | 'teamMember'
  | 'project'
  | 'projectMember'
  | 'state'
  | 'taskType'
  | 'field'
  | 'fieldValue'
  | 'baseline'
  | 'share'
  | 'label'
  | 'task'
  | 'relation'
  | 'cycle'
  | 'module'
  | 'page'
  | 'comment'
  | 'attachment'
  | 'view'
  | 'timeEntry'
  | 'template'
  | 'automation'
  | 'webhook'
  | 'notification'
  | 'activity'
  | 'intake'
  | 'purge';

export interface EntityDef {
  /** SQL table name. */
  table: string;
  /** Mutable fields that participate in last-writer-wins merging. */
  fields: readonly string[];
  /** Fields only the server may write. Clients that try are ignored. */
  serverOnly?: readonly string[];
  /**
   * Fields that never leave the server at all — not written by a client and
   * not sent to one. A signing secret is the case: the receiver has it, and
   * nobody's browser needs it.
   */
  secret?: readonly string[];
  /** Entity rows are never created or edited by clients. */
  readOnly?: boolean;
  /** Rows belong to a single user and are not shared with the workspace. */
  private?: boolean;
  /** Columns holding JSON-encoded values. */
  json?: readonly string[];
}

export const ENTITIES = {
  user: {
    table: 'users',
    fields: ['name', 'email', 'avatar_url', 'timezone', 'locale', 'bio', 'digest'],
    readOnly: true,
  },
  member: {
    table: 'workspace_members',
    fields: ['workspace_id', 'user_id', 'role'],
    readOnly: true,
  },
  team: {
    table: 'teams',
    fields: ['workspace_id', 'name', 'key', 'description', 'icon', 'color', 'archived'],
  },
  teamMember: {
    table: 'team_members',
    fields: ['workspace_id', 'team_id', 'user_id', 'role'],
  },
  project: {
    table: 'projects',
    fields: [
      'workspace_id', 'team_id', 'parent_id', 'name', 'key', 'description', 'icon', 'color',
      'lead_id', 'start_date', 'target_date', 'status', 'visibility', 'archived',
      'default_state_id', 'default_view_id', 'sort_order',
    ],
  },
  projectMember: {
    table: 'project_members',
    fields: ['workspace_id', 'project_id', 'user_id', 'role'],
  },
  state: {
    table: 'states',
    fields: [
      'workspace_id', 'project_id', 'name', 'group_key', 'color', 'sort_order',
      'wip_limit', 'allowed_roles',
    ],
    json: ['allowed_roles'],
  },
  taskType: {
    table: 'task_types',
    fields: ['workspace_id', 'project_id', 'name', 'icon', 'color', 'is_default', 'sort_order'],
  },
  /**
   * A field a project adds to its tasks. `type_ids` is what OpenProject calls a
   * type-dependent field: empty means every work item type, otherwise only
   * those — a Bug asks for steps to reproduce, a Feature does not.
   */
  field: {
    table: 'custom_fields',
    fields: [
      'workspace_id', 'project_id', 'name', 'kind', 'options', 'type_ids',
      'help', 'required', 'show_in_table', 'archived', 'sort_order',
    ],
    json: ['options', 'type_ids'],
  },
  /**
   * One task's answer to one field. Its own row rather than a map on the task,
   * so two people filling in two different fields on the same task merge
   * instead of overwriting each other. The id is derived from the pair, so two
   * devices answering the same field offline converge on one row rather than
   * two.
   */
  fieldValue: {
    table: 'field_values',
    fields: ['workspace_id', 'project_id', 'task_id', 'field_id', 'value'],
  },
  label: {
    table: 'labels',
    fields: ['workspace_id', 'project_id', 'name', 'color', 'description'],
  },
  task: {
    table: 'tasks',
    fields: [
      'workspace_id', 'project_id', 'title', 'description', 'state_id', 'type_id', 'priority',
      'assignees', 'labels', 'parent_id', 'cycle_id', 'module_id', 'estimate',
      'start_date', 'due_date', 'sort_order', 'completed_at', 'archived', 'created_by',
      'subscribers', 'recurrence', 'recurred_from',
    ],
    serverOnly: ['number', 'identifier'],
    json: ['assignees', 'labels', 'subscribers'],
  },
  /**
   * A plan, kept. Dates as they were on the day it was taken, so the chart can
   * draw what was promised behind what is happening.
   */
  baseline: {
    table: 'baselines',
    fields: ['workspace_id', 'project_id', 'name', 'taken_at', 'entries'],
    json: ['entries'],
  },
  /**
   * A link that lets somebody outside the workspace read one thing.
   *
   * The token is the whole of the authorisation, so it is generated by the
   * server and never accepted from a client — a share whose secret the caller
   * chose is a share somebody else can guess.
   */
  share: {
    table: 'shares',
    fields: [
      'workspace_id', 'project_id', 'kind', 'page_id', 'view_id',
      'name', 'expires_at', 'include_done', 'created_by',
    ],
    serverOnly: ['token', 'views', 'last_seen_at'],
  },
  relation: {
    table: 'task_relations',
    fields: ['workspace_id', 'task_id', 'related_task_id', 'kind'],
  },
  cycle: {
    table: 'cycles',
    fields: ['workspace_id', 'project_id', 'name', 'description', 'start_date', 'end_date', 'status'],
  },
  module: {
    table: 'modules',
    fields: [
      'workspace_id', 'project_id', 'name', 'description', 'lead_id',
      'start_date', 'target_date', 'status', 'sort_order',
    ],
  },
  page: {
    table: 'pages',
    fields: [
      'workspace_id', 'project_id', 'parent_id', 'title', 'icon', 'content',
      'sort_order', 'archived', 'access', 'labels', 'watchers', 'is_template',
      'created_by', 'cover_url',
    ],
    json: ['labels', 'watchers'],
  },
  comment: {
    table: 'comments',
    fields: ['workspace_id', 'task_id', 'page_id', 'parent_id', 'body', 'author_id', 'reactions', 'anchor'],
    json: ['reactions', 'anchor'],
  },
  attachment: {
    table: 'attachments',
    fields: [
      'workspace_id', 'task_id', 'page_id', 'comment_id', 'name', 'mime', 'size',
      'url', 'thumb_url', 'width', 'height', 'uploaded_by',
    ],
  },
  view: {
    table: 'views',
    fields: [
      'workspace_id', 'project_id', 'team_id', 'name', 'icon', 'layout',
      'filters', 'group_by', 'order_by', 'show_done', 'shared', 'owner_id', 'sort_order',
    ],
    json: ['filters'],
  },
  timeEntry: {
    table: 'time_entries',
    fields: [
      'workspace_id', 'project_id', 'task_id', 'user_id', 'minutes', 'spent_on',
      'note', 'started_at', 'billable',
    ],
  },
  template: {
    table: 'templates',
    fields: [
      'workspace_id', 'project_id', 'name', 'kind', 'icon', 'title', 'description',
      'priority', 'labels', 'assignees', 'estimate', 'subtasks', 'target_project_id',
      'due_in_days', 'archived', 'sort_order',
    ],
    json: ['labels', 'assignees', 'subtasks'],
  },
  automation: {
    table: 'automations',
    fields: [
      'workspace_id', 'project_id', 'name', 'enabled', 'trigger_kind', 'trigger_state_id',
      'trigger_days', 'action_kind', 'action_patch',
      'trigger_group', 'template_id', 'recipients', 'fan_out', 'exclude_actor',
      'link_kind', 'apply_to_generated', 'once', 'sort_order',
    ],
    json: ['recipients'],
  },
  webhook: {
    table: 'webhooks',
    fields: ['workspace_id', 'project_id', 'name', 'url', 'events', 'enabled', 'direction', 'format'],
    /** The delivery result is worth showing; it is just not the client's to set. */
    serverOnly: ['last_status', 'last_error', 'last_sent_at'],
    /** The signing secret is the receiver's and this server's. Nobody else's. */
    secret: ['secret'],
  },
  notification: {
    table: 'notifications',
    fields: ['workspace_id', 'user_id', 'kind', 'title', 'body', 'task_id', 'page_id', 'project_id', 'actor_id', 'read_at', 'archived_at'],
    serverOnly: ['workspace_id', 'user_id', 'kind', 'title', 'body', 'task_id', 'page_id', 'actor_id'],
    private: true,
  },
  activity: {
    table: 'activities',
    fields: ['workspace_id', 'project_id', 'task_id', 'page_id', 'actor_id', 'verb', 'field', 'old_value', 'new_value'],
    readOnly: true,
  },
  /**
   * Something reported from outside, before anybody has decided it is work.
   *
   * Written by an anonymous form and never by a client, so `readOnly`: the
   * things a member does to one — accept it, decline it — go through their own
   * route, because accepting is a task being created and that is not a field.
   */
  intake: {
    table: 'intakes',
    fields: [
      'workspace_id', 'project_id', 'share_id', 'reporter', 'email',
      'title', 'body', 'status', 'task_id', 'handled_by', 'handled_at',
    ],
    readOnly: true,
  },
  /**
   * A tombstone that has itself been thrown away.
   *
   * Deleting a row here means stamping `deleted_at` and letting the tombstone
   * keep syncing — that is the only way two devices ever agree something is
   * gone. So emptying the trash cannot simply drop the row: a device that has
   * it would show it in *its* trash forever and could put it back.
   *
   * This is the marker that says the tombstone is finished with. It syncs like
   * anything else, and a client that receives one deletes its copy of the row
   * it names. Tiny, and kept: it is the only record that the thing ever existed.
   */
  purge: {
    table: 'purges',
    fields: ['workspace_id', 'entity', 'row_id', 'reason'],
    readOnly: true,
  },
} as const satisfies Record<EntityName, EntityDef>;

export const ENTITY_NAMES = Object.keys(ENTITIES) as EntityName[];

/** Columns present on every syncable table. */
export const SYSTEM_FIELDS = ['id', 'created_at', 'updated_at', 'deleted_at', 'seq', 'clocks'] as const;

export function entityDef(name: string): EntityDef | undefined {
  return (ENTITIES as Record<string, EntityDef>)[name];
}

export function tableFor(name: EntityName): string {
  return ENTITIES[name].table;
}

/**
 * The URL segment each entity is served under.
 *
 * Here rather than in the server's routes because the client needs it too: when
 * the server rejects a mutation, the client has to re-read the row it was wrong
 * about, and it can only do that if both sides agree on the word.
 */
export const COLLECTIONS: Record<EntityName, string> = {
  user: 'users',
  member: 'members',
  team: 'teams',
  teamMember: 'team-members',
  project: 'projects',
  projectMember: 'project-members',
  state: 'states',
  taskType: 'task-types',
  field: 'fields',
  fieldValue: 'field-values',
  baseline: 'baselines',
  share: 'shares',
  label: 'labels',
  task: 'tasks',
  relation: 'relations',
  cycle: 'cycles',
  module: 'modules',
  page: 'pages',
  comment: 'comments',
  attachment: 'attachments',
  view: 'views',
  timeEntry: 'time-entries',
  template: 'templates',
  automation: 'automations',
  webhook: 'webhooks',
  notification: 'notifications',
  activity: 'activities',
  intake: 'intakes',
  purge: 'purges',
};
